#!/bin/bash
##################################################################################
# This script was generated by CSVComparatorGUI:
#		http://sourceforge.net/projects/csvcomparator/
# 
# Compare CSV Files
# ------------------------------------
# This script will compare the CSV-Files set in the variables.
# This script takes no arguments, please set the variables in the script.
#
##################################################################################

# Check if there are no arguments present
if [ "$#" -ne 0 ]
then
    ###########################################################
    # Print Help
    ###########################################################
    echo "This script takes no arguments, set the variables in the script."

    exit 1
else

    ###########################################################
    # Set Configuration
    # -----------------
    # If you run the script under windows using cygwin, please
    # make sure to specify a cygwin path for "JAVA" and a 
    # windows path for "CSVCOMPARE_JAR".
    ###########################################################
    
    ##### Java Environment Configration #####
    JAVA='/cygdrive/c/Program Files (x86)/Java/jre7/bin/java'
    CSVCOMPARE_JAR='C:\Program Files\CSVComparator\CSVComparatorCLI.jar'

    #older File
    OLDER_FILE='./testdata/older_topLevel.csv'
    OLDER_LABEL='old'
    OLDER_DELIMITER='#'
    OLDER_QUOTES='true'
        
    #newer File
    YOUNGER_FILE='./testdata/younger_topLevel.csv'
    YOUNGER_LABEL='young'
    YOUNGER_DELIMITER=','
    YOUNGER_QUOTES='true'
    
    ###########################################################
    # Compare Files
    ###########################################################
    
    "${JAVA}" -jar "${CSVCOMPARE_JAR}"\
					"-older.file=${OLDER_FILE}"\
					"-older.delimiter=${OLDER_DELIMITER}"\
					"-older.quotes=${OLDER_QUOTES}"\
					"-older.label=${OLDER_LABEL}"\
					"-younger.file=${YOUNGER_FILE}"\
					"-younger.delimiter=${YOUNGER_DELIMITER}"\
					"-younger.quotes=${YOUNGER_QUOTES}"\
					"-younger.label=${YOUNGER_LABEL}"\
					"-column.identifier=Count,Description"\
					"-result.file=./testdata/_result.csv"\
					"-result.delimiter=,"\
					"-result.sort=false"\
					"-result.quotes=true"\
					"-column.identifier.makeunique=false"\
					"-column.toplevel=Level,Level,Top"\
					"-column.compareDef=Description,Description,printOlder(),printYounger(),compareDifference(),compareDifference%(),compareAsStrings(),printSeparator()"\
					"-column.compareDef=Count,Count,divideOlderBy(2),printYounger(),printOlder(),compareDifference(),compareAsStrings()"\
					"-column.compareDef=Level,Level,divideYoungerBy(3),printOlder(),compareDifference%(),printSeparator()"\
					"-column.compareDef=Level,Count,multiplyOlderBy(4),printYounger()"\
					"-column.compareDef=Level,Description,multiplyYoungerBy(5),printMerged()"\
					"-column.compareDef=Description,Count"\
					"-result.comparediff=true"\
					"-result.comparediff%=false"\
					"-result.comparestring=true"\
					"-config.loglevel.console=INFO"
fi
