#!/bin/bash
##################################################################################
# This script was generated by CSVComparatorGUI:
#		http://sourceforge.net/projects/csvcomparator/
# 
# Compare CSV Files
# ------------------------------------
# This script will compare the CSV-Files set in the variables.
# This script takes no arguments, please set the variables in the script.
#
##################################################################################

# Check if there are no arguments present
if [ "$#" -ne 0 ]
then
    ###########################################################
    # Print Help
    ###########################################################
    echo "This script takes no arguments, set the variables in the script."

    exit 1
else

    ###########################################################
    # Set Configuration
    # -----------------
    # If you run the script under windows using cygwin, please
    # make sure to specify a cygwin path for "JAVA" and a 
    # windows path for "CSVCOMPARE_JAR".
    ###########################################################
    
    ##### Java Environment Configration #####
    JAVA='/cygdrive/c/Program Files (x86)/Java/jre7/bin/java'
    CSVCOMPARE_JAR='C:\Program Files\CSVComparator\CSVComparatorCLI.jar'

    #older File
    OLDER_FILE='<<olderFile>>'
    OLDER_LABEL='<<olderLabel>>'
    OLDER_DELIMITER='<<olderDelimiter>>'
    OLDER_QUOTES='<<olderQuotes>>'
        
    #newer File
    YOUNGER_FILE='<<youngerFile>>'
    YOUNGER_LABEL='<<youngerLabel>>'
    YOUNGER_DELIMITER='<<youngerDelimiter>>'
    YOUNGER_QUOTES='<<youngerQuotes>>'
    
    ###########################################################
    # Compare Files
    ###########################################################
    
    "${JAVA}" -jar "${CSVCOMPARE_JAR}"\
					"-older.file=${OLDER_FILE}"\
					"-older.delimiter=${OLDER_DELIMITER}"\
					"-older.quotes=${OLDER_QUOTES}"\
					"-older.label=${OLDER_LABEL}"\
					"-younger.file=${YOUNGER_FILE}"\
					"-younger.delimiter=${YOUNGER_DELIMITER}"\
					"-younger.quotes=${YOUNGER_QUOTES}"\
					"-younger.label=${YOUNGER_LABEL}"\
					"-column.identifier=<<identifierColumn>>"\
<<generalSettings>><<columnDefinitions>><<defaultComparison>>					"-config.loglevel.console=INFO"
fi
